export class BotEngine {
  constructor({trading,currency,onEvent}){this.trading=trading;this.currency=currency;this.onEvent=onEvent||(()=>{});this.running=false;this.symbol='R_10';this.contractType='DIGITDIFF';this.stake=1;this.baseStake=1;this.duration=1;this.barrier=1;this.multiplier=2;this.lossLimit=3;this.losses=0;this.currentContract=null;this.resultWaiters=new Map();this.flow=[];this.lastDigit=null;this.previousDigit=null;this.tickWaiters=[];}
  emit(type,message,data={}){this.onEvent({type,message,...data});}
  handleTick(tick){const quote=Number(tick?.quote);if(!Number.isFinite(quote))return;const digits=String(tick.quote).replace(/[^0-9]/g,'');if(!digits)return;this.previousDigit=this.lastDigit;this.lastDigit=Number(digits.slice(-1));this.emit('tick',`Tick ${tick.quote} · digit ${this.lastDigit}`,{tick,lastDigit:this.lastDigit,previousDigit:this.previousDigit});this.tickWaiters.splice(0).forEach(r=>r());}
  waitForTick(timeout=30000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{const i=this.tickWaiters.indexOf(done);if(i>=0)this.tickWaiters.splice(i,1);reject(new Error('Timed out waiting for a live tick'));},timeout);const done=()=>{clearTimeout(timer);resolve();};this.tickWaiters.push(done);});}
  parse(xmlText){const doc=new DOMParser().parseFromString(xmlText,'text/xml');const blocks=[...doc.querySelectorAll('block')];const field=(type,name,def)=>blocks.find(b=>b.getAttribute('type')===type)?.querySelector(`field[name="${name}"]`)?.textContent??def;this.symbol=field('digit_strategy','SYMBOL',this.symbol);this.contractType=field('digit_contract','CONTRACT',this.contractType);this.barrier=Number(field('digit_barrier','BARRIER',this.barrier));this.stake=Number(field('digit_stake','STAKE',this.stake));this.baseStake=this.stake;this.duration=Number(field('digit_duration','DURATION',this.duration));this.multiplier=Number(field('digit_recovery','MULTIPLIER',this.multiplier));this.lossLimit=Number(field('recovery_stop','LOSSES',this.lossLimit));this.flow=this.readFlow(doc);return doc;}
  readFlow(doc){const root=doc.querySelector('block[type="before_purchase"]');if(!root)return[];const out=[];let b=root;const seen=new Set();while(b&&!seen.has(b)){seen.add(b);out.push(b);b=b.querySelector(':scope > next > block');}return out;}
  async waitForResult(id,timeout=120000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.resultWaiters.delete(String(id));reject(new Error('Timed out waiting for contract result'));},timeout);this.resultWaiters.set(String(id),{resolve,reject,timer});});}
  handleMessage(data){const p=data?.proposal_open_contract;if(!p)return;const id=String(p.contract_id||'');if(!id)return;if(p.current_spot!==undefined){const s=String(p.current_spot).replace(/[^0-9]/g,'');if(s)this.lastDigit=Number(s.slice(-1));}const done=p.is_sold||['won','lost','sold'].includes(String(p.status));if(done){const w=this.resultWaiters.get(id);if(w){clearTimeout(w.timer);this.resultWaiters.delete(id);w.resolve(p);}}}
  evaluateCompare(block){const leftBlock=block.querySelector(':scope > value[name="LEFT"] > block');const rightBlock=block.querySelector(':scope > value[name="RIGHT"] > block');const valueOf=b=>{if(!b)return this.lastDigit;const type=b.getAttribute('type');if(type==='market_tick')return this.lastDigit;if(type==='previous_digit')return this.previousDigit;if(type==='math_number')return Number(b.querySelector('field')?.textContent??0);return this.lastDigit;};const left=Number(valueOf(leftBlock));const right=Number(valueOf(rightBlock));const op=block.querySelector(':scope > field[name="OP"]')?.textContent||'EQ';return op==='EQ'?left===right:op==='NEQ'?left!==right:op==='GT'?left>right:op==='LT'?left<right:op==='GTE'?left>=right:left<=right;}
  evaluateTickBlocks(doc){for(const b of [...doc.querySelectorAll('block[type="tick_even_odd"]')]){const parity=b.querySelector('field[name="PARITY"]')?.textContent||'EVEN';const ok=this.lastDigit!==null&&(this.lastDigit%2===0)===(parity==='EVEN');this.emit('condition',`${parity} condition ${ok?'TRUE':'FALSE'}`,{result:ok,lastDigit:this.lastDigit});if(!ok)return false;}for(const b of [...doc.querySelectorAll('block[type="tick_over_under"]')]){const direction=b.querySelector('field[name="DIRECTION"]')?.textContent||'OVER';const digit=Number(b.querySelector('field[name="DIGIT"]')?.textContent??5);const ok=this.lastDigit!==null&&(direction==='OVER'?this.lastDigit>digit:this.lastDigit<digit);this.emit('condition',`${direction} ${digit} ${ok?'TRUE':'FALSE'}`,{result:ok,lastDigit:this.lastDigit});if(!ok)return false;}return true;}
  async runConditionalBlocks(doc){if(this.lastDigit===null)await this.waitForTick();if(!this.evaluateTickBlocks(doc))return false;for(const b of [...doc.querySelectorAll('block[type="digit_compare"]')]){const ok=this.evaluateCompare(b);this.emit('condition',`Digit condition ${ok?'TRUE':'FALSE'}`,{result:ok,lastDigit:this.lastDigit,previousDigit:this.previousDigit});}for(const b of [...doc.querySelectorAll('block[type="controls_if"]')]){const compare=b.querySelector(':scope > value[name="IF0"] > block[type="digit_compare"]');if(compare&&!this.evaluateCompare(compare)){this.emit('condition','IF condition false · branch skipped');return false;}}return true;}
  async execute(xmlText){if(!this.trading)throw new Error('Trading connection is not ready');if(!xmlText)throw new Error('Build a bot before running it');const doc=this.parse(xmlText);this.running=true;this.losses=0;this.emit('start',`Bot started · ${this.symbol} · ${this.contractType}`,{symbol:this.symbol,contractType:this.contractType,stake:this.stake,duration:this.duration,barrier:this.barrier,flow:this.flow.map(b=>b.getAttribute('type'))});while(this.running){if(this.losses>=this.lossLimit){this.emit('limit','Loss limit reached · bot stopped',{losses:this.losses});break;}const allowed=await this.runConditionalBlocks(doc);if(!allowed){this.emit('condition','Live tick condition not met · waiting for next tick');await this.waitForTick();continue;}const proposal=await this.trading.proposal({symbol:this.symbol,contractType:this.contractType,amount:this.stake,currency:this.currency,duration:this.duration,durationUnit:'t',basis:'stake',barrier:this.barrier});if(!this.running)break;const bought=await this.trading.buy(proposal.id,proposal.ask_price);this.currentContract=bought;this.emit('buy',`Contract purchased · ${bought.contract_id||bought.transaction_id}`,{contract:bought});if(!bought.contract_id)throw new Error('Deriv did not return a contract ID');await this.trading.openContract(bought.contract_id);const result=await this.waitForResult(bought.contract_id);const profit=Number(result.profit||0);const won=String(result.status).toLowerCase()==='won'||profit>0;this.emit('result',`${won?'WIN':'LOSS'} · ${profit}`,{result,won,profit});if(won){this.losses=0;this.stake=this.baseStake;}else{this.losses++;this.stake=this.baseStake*Math.pow(this.multiplier,this.losses);this.emit('recovery',`Loss ${this.losses} · next stake ${this.stake}`,{nextStake:this.stake});}if(this.flow.some(b=>b.getAttribute('type')==='stop_bot')&&this.losses>=this.lossLimit)break;if(this.flow.some(b=>b.getAttribute('type')==='reset_stake')&&won)this.stake=this.baseStake;}this.running=false;this.emit('stop','Bot stopped',{losses:this.losses});return this.currentContract;}
  stop(){this.running=false;this.tickWaiters.splice(0).forEach(r=>r());this.emit('stop','Bot stopped');}
}
