export class BotEngine {
  constructor({ trading, currency, onEvent }) { this.trading=trading; this.currency=currency; this.onEvent=onEvent||(()=>{}); this.running=false; this.symbol='R_10'; this.contractType='DIGITDIFF'; this.stake=1; this.baseStake=1; this.duration=1; this.barrier=1; this.multiplier=2; this.lossLimit=3; this.losses=0; this.currentContract=null; this.resultWaiters=new Map(); this.flow=[]; }
  emit(type,message,data={}){this.onEvent({type,message,...data});}
  parse(xmlText){const doc=new DOMParser().parseFromString(xmlText,'text/xml');const blocks=[...doc.querySelectorAll('block')];const field=(type,name,def)=>blocks.find(b=>b.getAttribute('type')===type)?.querySelector(`field[name="${name}"]`)?.textContent??def;this.symbol=field('digit_strategy','SYMBOL',this.symbol);this.contractType=field('digit_contract','CONTRACT',this.contractType);this.barrier=Number(field('digit_barrier','BARRIER',this.barrier));this.stake=Number(field('digit_stake','STAKE',this.stake));this.baseStake=this.stake;this.duration=Number(field('digit_duration','DURATION',this.duration));this.multiplier=Number(field('digit_recovery','MULTIPLIER',this.multiplier));this.lossLimit=Number(field('recovery_stop','LOSSES',this.lossLimit));this.flow=this.readFlow(doc);return {blocks};}
  readFlow(doc){const root=doc.querySelector('block[type="before_purchase"]');if(!root)return[];const flow=[];let b=root;const seen=new Set();while(b&&!seen.has(b)){seen.add(b);flow.push(b.getAttribute('type'));b=b.querySelector(':scope > next > block');}return flow;}
  async waitForResult(contractId,timeout=120000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.resultWaiters.delete(String(contractId));reject(new Error('Timed out waiting for contract result'));},timeout);this.resultWaiters.set(String(contractId),{resolve,reject,timer});});}
  handleMessage(data){const p=data?.proposal_open_contract;if(!p)return;const id=String(p.contract_id||'');if(!id)return;const done=p.is_sold||['won','lost','sold'].includes(String(p.status));if(!done)return;const waiter=this.resultWaiters.get(id);if(waiter){clearTimeout(waiter.timer);this.resultWaiters.delete(id);waiter.resolve(p);}}
  async runFlow(type){if(!this.flow.length)return true;if(type==='before_purchase'){this.emit('flow','Before Purchase');return true;}if(type==='after_purchase'){this.emit('flow','After Purchase');return true;}if(type==='after_contract'){this.emit('flow','After Contract');return true;}if(type==='reset_stake'){this.stake=this.baseStake;this.emit('flow',`Stake reset · ${this.stake}`);return true;}if(type==='stop_bot'){this.running=false;this.emit('flow','Stop block reached');return false;}if(type==='restart_bot'){this.emit('flow','Restart block reached');return true;}return true;}
  async execute(xmlText){if(!this.trading)throw new Error('Trading connection is not ready');if(!xmlText)throw new Error('Build a bot before running it');this.parse(xmlText);this.running=true;this.losses=0;this.emit('start',`Bot started · ${this.symbol} · ${this.contractType}`,{symbol:this.symbol,contractType:this.contractType,stake:this.stake,duration:this.duration,barrier:this.barrier,flow:this.flow});
    while(this.running){if(this.losses>=this.lossLimit){this.emit('limit','Loss limit reached · bot stopped',{losses:this.losses});break;}await this.runFlow('before_purchase');if(!this.running)break;const proposal=await this.trading.proposal({symbol:this.symbol,contractType:this.contractType,amount:this.stake,currency:this.currency,duration:this.duration,durationUnit:'t',basis:'stake',barrier:this.barrier});if(!this.running)break;this.emit('proposal','Proposal received',{proposal});const bought=await this.trading.buy(proposal.id,proposal.ask_price);this.currentContract=bought;const id=bought.contract_id||bought.transaction_id;this.emit('buy',`Contract purchased · ${id}`,{contract:bought});await this.runFlow('after_purchase');if(!bought.contract_id)throw new Error('Deriv did not return a contract ID');await this.trading.openContract(bought.contract_id);const result=await this.waitForResult(bought.contract_id);const profit=Number(result.profit||0);const won=String(result.status).toLowerCase()==='won'||profit>0;this.emit('result',`${won?'WIN':'LOSS'} · ${profit}`,{result,won,profit,losses:this.losses});if(won){this.losses=0;this.stake=this.baseStake;}else{this.losses+=1;this.stake=this.baseStake*Math.pow(this.multiplier,this.losses);this.emit('recovery',`Loss ${this.losses} · next stake ${this.stake}`,{losses:this.losses,nextStake:this.stake});}await this.runFlow('after_contract');if(!this.running)break;if(this.flow.includes('reset_stake')&&won)await this.runFlow('reset_stake');if(this.flow.includes('stop_bot')&&this.losses>=this.lossLimit){await this.runFlow('stop_bot');break;}if(this.flow.includes('restart_bot'))await this.runFlow('restart_bot');}
    this.running=false;this.emit('stop','Bot stopped',{losses:this.losses});return this.currentContract;}
  stop(){this.running=false;this.emit('stop','Bot stopped');}
}
